### ISSUE TITLE
Libary problems with CodeSYS

### ISSUE THREAD

**Issue by BlackJaecky** [stefandreyer/I2C-Multiplex#1]
Hi,
i tried to include your libary for I2C in Codesys, but i always get problems that Codesys cannot resolve different libaries.
I tried to install all sorts of libaries, but can't get it to work. Could you tell me what the best way is to install and include the libary?

I'm using CodeSYS V3.5 SP14
Control for Raspberry PI 3.5.14.10

**Comment by stefandreyer** [comment]
Hi BlackJaecky,

all needed library can be found in my repositorys, please install them an then let me know if still something is missing.

BR Stefan
